### PR TITLE
Django migrations and 1.8 imports, PEP8 cleanup, and small fixups

### PR DESCRIPTION
**Pull request by blag**
There's a lot of unrelated changes, but they're all backwards compatible and fairly straightforward to review.

Comments welcome. :smile:

### CODE REVIEW

**Comment by laiyonghao** [comment]
it works fine with django 1.8. merge it, plz.

**Comment by areski** [comment]
I badly need this too! @jschrewe any plan to merge?

**Comment by arthanson** [comment]
@blag I've merged a separate Django 1.8 fix for GenericAdmin, can you make a pull request with that removed and also remove all the extra stuff from the .gitignore.  I'll merge it then then create a new release for Django 1.9

**Comment by blag** [comment]
@arthanson: I split up my commits into #32 and #33 - let me know if you would like me to split out anything else. If not, this PR can be closed. Thanks!

**Comment by arthanson** [comment]
Closing this as separate pr requests have been created

**Pull request closed without merging**
